// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/images/v1/images.proto

package images

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Images_CreateImage_FullMethodName  = "/cubelet.services.images.v1.Images/CreateImage"
	Images_ListImages_FullMethodName   = "/cubelet.services.images.v1.Images/ListImages"
	Images_DestroyImage_FullMethodName = "/cubelet.services.images.v1.Images/DestroyImage"
	Images_VolumeUtils_FullMethodName  = "/cubelet.services.images.v1.Images/VolumeUtils"
)

// ImagesClient is the client API for Images service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for handling image operations.
type ImagesClient interface {
	CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*CreateImageRequestResponse, error)
	// cubelet v1 not support list and destroy image
	ListImages(ctx context.Context, in *CubeListImageRequest, opts ...grpc.CallOption) (*CubeListImageResponse, error)
	DestroyImage(ctx context.Context, in *DestroyImageRequest, opts ...grpc.CallOption) (*DestroyImageResponse, error)
	VolumeUtils(ctx context.Context, in *VolumUtilsRequest, opts ...grpc.CallOption) (*VolumUtilsResponse, error)
}

type imagesClient struct {
	cc grpc.ClientConnInterface
}

func NewImagesClient(cc grpc.ClientConnInterface) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*CreateImageRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateImageRequestResponse)
	err := c.cc.Invoke(ctx, Images_CreateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) ListImages(ctx context.Context, in *CubeListImageRequest, opts ...grpc.CallOption) (*CubeListImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CubeListImageResponse)
	err := c.cc.Invoke(ctx, Images_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) DestroyImage(ctx context.Context, in *DestroyImageRequest, opts ...grpc.CallOption) (*DestroyImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyImageResponse)
	err := c.cc.Invoke(ctx, Images_DestroyImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) VolumeUtils(ctx context.Context, in *VolumUtilsRequest, opts ...grpc.CallOption) (*VolumUtilsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VolumUtilsResponse)
	err := c.cc.Invoke(ctx, Images_VolumeUtils_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagesServer is the server API for Images service.
// All implementations must embed UnimplementedImagesServer
// for forward compatibility.
//
// Service for handling image operations.
type ImagesServer interface {
	CreateImage(context.Context, *CreateImageRequest) (*CreateImageRequestResponse, error)
	// cubelet v1 not support list and destroy image
	ListImages(context.Context, *CubeListImageRequest) (*CubeListImageResponse, error)
	DestroyImage(context.Context, *DestroyImageRequest) (*DestroyImageResponse, error)
	VolumeUtils(context.Context, *VolumUtilsRequest) (*VolumUtilsResponse, error)
	mustEmbedUnimplementedImagesServer()
}

// UnimplementedImagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImagesServer struct{}

func (UnimplementedImagesServer) CreateImage(context.Context, *CreateImageRequest) (*CreateImageRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImage not implemented")
}
func (UnimplementedImagesServer) ListImages(context.Context, *CubeListImageRequest) (*CubeListImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImagesServer) DestroyImage(context.Context, *DestroyImageRequest) (*DestroyImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyImage not implemented")
}
func (UnimplementedImagesServer) VolumeUtils(context.Context, *VolumUtilsRequest) (*VolumUtilsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VolumeUtils not implemented")
}
func (UnimplementedImagesServer) mustEmbedUnimplementedImagesServer() {}
func (UnimplementedImagesServer) testEmbeddedByValue()                {}

// UnsafeImagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImagesServer will
// result in compilation errors.
type UnsafeImagesServer interface {
	mustEmbedUnimplementedImagesServer()
}

func RegisterImagesServer(s grpc.ServiceRegistrar, srv ImagesServer) {
	// If the following call panics, it indicates UnimplementedImagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Images_ServiceDesc, srv)
}

func _Images_CreateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).CreateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_CreateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).CreateImage(ctx, req.(*CreateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CubeListImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).ListImages(ctx, req.(*CubeListImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_DestroyImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).DestroyImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_DestroyImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).DestroyImage(ctx, req.(*DestroyImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_VolumeUtils_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumUtilsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).VolumeUtils(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Images_VolumeUtils_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).VolumeUtils(ctx, req.(*VolumUtilsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Images_ServiceDesc is the grpc.ServiceDesc for Images service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Images_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.images.v1.Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateImage",
			Handler:    _Images_CreateImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _Images_ListImages_Handler,
		},
		{
			MethodName: "DestroyImage",
			Handler:    _Images_DestroyImage_Handler,
		},
		{
			MethodName: "VolumeUtils",
			Handler:    _Images_VolumeUtils_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/images/v1/images.proto",
}
