// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/images/v1/images.proto

package images

import (
	v1 "github.com/tencentcloud/CubeSandbox/CubeMaster/api/services/errorcode/v1"
	v11 "github.com/tencentcloud/CubeSandbox/CubeMaster/api/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageStorageMediaType int32

const (
	// Docker means normal oci container images.should be pulled from dockerhub
	ImageStorageMediaType_docker ImageStorageMediaType = 0
	// image from local disk in ext4 format rootfs.
	ImageStorageMediaType_ext4 ImageStorageMediaType = 1
)

// Enum value maps for ImageStorageMediaType.
var (
	ImageStorageMediaType_name = map[int32]string{
		0: "docker",
		1: "ext4",
	}
	ImageStorageMediaType_value = map[string]int32{
		"docker": 0,
		"ext4":   1,
	}
)

func (x ImageStorageMediaType) Enum() *ImageStorageMediaType {
	p := new(ImageStorageMediaType)
	*p = x
	return p
}

func (x ImageStorageMediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageStorageMediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_images_v1_images_proto_enumTypes[0].Descriptor()
}

func (ImageStorageMediaType) Type() protoreflect.EnumType {
	return &file_api_services_images_v1_images_proto_enumTypes[0]
}

func (x ImageStorageMediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageStorageMediaType.Descriptor instead.
func (ImageStorageMediaType) EnumDescriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{0}
}

// Policy for pulling OCI objects. Possible values are:
// Always: the kubelet always attempts to pull the reference. Container creation will fail If the pull fails.
// Never: the kubelet never pulls the reference and only uses a local image or artifact. Container creation will fail if the reference isn't present.
// IfNotPresent: the kubelet pulls if the reference isn't already present on disk. Container creation will fail if the reference isn't present and the pull fails.
// Defaults to Always if :latest tag is specified, or IfNotPresent otherwise.
// +optional
type PullPolicy int32

const (
	// PullAlways means that kubelet always attempts to pull the latest image. Container will fail If the pull fails.
	PullPolicy_Always PullPolicy = 0
	// PullNever means that kubelet never pulls an image, but only uses a local image. Container will fail if the image isn't present
	PullPolicy_Never PullPolicy = 1
	// PullIfNotPresent means that kubelet pulls if the image isn't present on disk. Container will fail if the image isn't present and the pull fails.
	PullPolicy_IfNotPresent PullPolicy = 2
)

// Enum value maps for PullPolicy.
var (
	PullPolicy_name = map[int32]string{
		0: "Always",
		1: "Never",
		2: "IfNotPresent",
	}
	PullPolicy_value = map[string]int32{
		"Always":       0,
		"Never":        1,
		"IfNotPresent": 2,
	}
)

func (x PullPolicy) Enum() *PullPolicy {
	p := new(PullPolicy)
	*p = x
	return p
}

func (x PullPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_images_v1_images_proto_enumTypes[1].Descriptor()
}

func (PullPolicy) Type() protoreflect.EnumType {
	return &file_api_services_images_v1_images_proto_enumTypes[1]
}

func (x PullPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPolicy.Descriptor instead.
func (PullPolicy) EnumDescriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{1}
}

type CreateImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID     string     `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Spec          *ImageSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{0}
}

func (x *CreateImageRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CreateImageRequest) GetSpec() *ImageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// ImageSpec is an internal representation of an image.
// ImageSpec defines the specification of an image
type ImageSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container's Image field (e.g. imageID or imageDigest).
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// annotations 传递username和token信息
	// ie. annotations["cube.image.username"] = xxx
	// ie. annotations["cube.image.token"] = xxx
	Annotations map[string]string `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Type of storage media for the image (docker/ext4)
	StorageMedia   string `protobuf:"bytes,3,opt,name=storage_media,json=storageMedia,proto3" json:"storage_media,omitempty"`
	Namespace      string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RuntimeHandler string `protobuf:"bytes,7,opt,name=runtime_handler,json=runtimeHandler,proto3" json:"runtime_handler,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageSpec) Reset() {
	*x = ImageSpec{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSpec) ProtoMessage() {}

func (x *ImageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSpec.ProtoReflect.Descriptor instead.
func (*ImageSpec) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{1}
}

func (x *ImageSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ImageSpec) GetStorageMedia() string {
	if x != nil {
		return x.StorageMedia
	}
	return ""
}

func (x *ImageSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ImageSpec) GetRuntimeHandler() string {
	if x != nil {
		return x.RuntimeHandler
	}
	return ""
}

// CreateImageRequestResponse contains the response for CreateImageRequest
type CreateImageRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier matching the request
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Result of the operation
	Ret           *v1.Ret `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequestResponse) Reset() {
	*x = CreateImageRequestResponse{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequestResponse) ProtoMessage() {}

func (x *CreateImageRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateImageRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{2}
}

func (x *CreateImageRequestResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CreateImageRequestResponse) GetRet() *v1.Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// DestroyImageRequest destroy image
type DestroyImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID     string     `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Spec          *ImageSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyImageRequest) Reset() {
	*x = DestroyImageRequest{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyImageRequest) ProtoMessage() {}

func (x *DestroyImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyImageRequest.ProtoReflect.Descriptor instead.
func (*DestroyImageRequest) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyImageRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *DestroyImageRequest) GetSpec() *ImageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// DestroyImageResponse destroy image
type DestroyImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Ret.
	Ret           *v1.Ret `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyImageResponse) Reset() {
	*x = DestroyImageResponse{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyImageResponse) ProtoMessage() {}

func (x *DestroyImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyImageResponse.ProtoReflect.Descriptor instead.
func (*DestroyImageResponse) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyImageResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *DestroyImageResponse) GetRet() *v1.Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// VolumUtilsRequest volum utils
type VolumUtilsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// cmd
	Cmd string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// input
	Input         string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumUtilsRequest) Reset() {
	*x = VolumUtilsRequest{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumUtilsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumUtilsRequest) ProtoMessage() {}

func (x *VolumUtilsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumUtilsRequest.ProtoReflect.Descriptor instead.
func (*VolumUtilsRequest) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{5}
}

func (x *VolumUtilsRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *VolumUtilsRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *VolumUtilsRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// VolumUtilsResponse volum utils
type VolumUtilsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Ret.
	Ret *v1.Ret `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	// output
	Output        string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumUtilsResponse) Reset() {
	*x = VolumUtilsResponse{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumUtilsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumUtilsResponse) ProtoMessage() {}

func (x *VolumUtilsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumUtilsResponse.ProtoReflect.Descriptor instead.
func (*VolumUtilsResponse) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{6}
}

func (x *VolumUtilsResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *VolumUtilsResponse) GetRet() *v1.Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *VolumUtilsResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type CubeListImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Filter to list images.
	Filter        *v11.ImageFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubeListImageRequest) Reset() {
	*x = CubeListImageRequest{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeListImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeListImageRequest) ProtoMessage() {}

func (x *CubeListImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeListImageRequest.ProtoReflect.Descriptor instead.
func (*CubeListImageRequest) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{7}
}

func (x *CubeListImageRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CubeListImageRequest) GetFilter() *v11.ImageFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CubeListImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requestID reqID
	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Ret.
	Ret *v1.Ret `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	// List of images.
	Images        []*v11.Image `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubeListImageResponse) Reset() {
	*x = CubeListImageResponse{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeListImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeListImageResponse) ProtoMessage() {}

func (x *CubeListImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeListImageResponse.ProtoReflect.Descriptor instead.
func (*CubeListImageResponse) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{8}
}

func (x *CubeListImageResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CubeListImageResponse) GetRet() *v1.Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *CubeListImageResponse) GetImages() []*v11.Image {
	if x != nil {
		return x.Images
	}
	return nil
}

// ImageVolumeSource represents a image volume resource.
type ImageVolumeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Image or artifact reference to be used.
	Reference     *ImageSpec `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	PullPolicy    PullPolicy `protobuf:"varint,2,opt,name=pullPolicy,proto3,enum=cubelet.services.images.v1.PullPolicy" json:"pullPolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVolumeSource) Reset() {
	*x = ImageVolumeSource{}
	mi := &file_api_services_images_v1_images_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVolumeSource) ProtoMessage() {}

func (x *ImageVolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_images_v1_images_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVolumeSource.ProtoReflect.Descriptor instead.
func (*ImageVolumeSource) Descriptor() ([]byte, []int) {
	return file_api_services_images_v1_images_proto_rawDescGZIP(), []int{9}
}

func (x *ImageVolumeSource) GetReference() *ImageSpec {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ImageVolumeSource) GetPullPolicy() PullPolicy {
	if x != nil {
		return x.PullPolicy
	}
	return PullPolicy_Always
}

var File_api_services_images_v1_images_proto protoreflect.FileDescriptor

const file_api_services_images_v1_images_proto_rawDesc = "" +
	"\n" +
	"#api/services/images/v1/images.proto\x12\x1acubelet.services.images.v1\x1a)api/services/errorcode/v1/errorcode.proto\x1a\x19api/types/v1/images.proto\"m\n" +
	"\x12CreateImageRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x129\n" +
	"\x04spec\x18\x02 \x01(\v2%.cubelet.services.images.v1.ImageSpecR\x04spec\"\xa7\x02\n" +
	"\tImageSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12X\n" +
	"\vannotations\x18\x02 \x03(\v26.cubelet.services.images.v1.ImageSpec.AnnotationsEntryR\vannotations\x12#\n" +
	"\rstorage_media\x18\x03 \x01(\tR\fstorageMedia\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12'\n" +
	"\x0fruntime_handler\x18\a \x01(\tR\x0eruntimeHandler\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x1aCreateImageRequestResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x124\n" +
	"\x03ret\x18\x02 \x01(\v2\".cubelet.services.errorcode.v1.RetR\x03ret\"n\n" +
	"\x13DestroyImageRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x129\n" +
	"\x04spec\x18\x02 \x01(\v2%.cubelet.services.images.v1.ImageSpecR\x04spec\"j\n" +
	"\x14DestroyImageResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x124\n" +
	"\x03ret\x18\x02 \x01(\v2\".cubelet.services.errorcode.v1.RetR\x03ret\"Y\n" +
	"\x11VolumUtilsRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"\x80\x01\n" +
	"\x12VolumUtilsResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x124\n" +
	"\x03ret\x18\x02 \x01(\v2\".cubelet.services.errorcode.v1.RetR\x03ret\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"h\n" +
	"\x14CubeListImageRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x122\n" +
	"\x06filter\x18\x02 \x01(\v2\x1a.cubelet.types.ImageFilterR\x06filter\"\x99\x01\n" +
	"\x15CubeListImageResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x124\n" +
	"\x03ret\x18\x02 \x01(\v2\".cubelet.services.errorcode.v1.RetR\x03ret\x12,\n" +
	"\x06images\x18\x03 \x03(\v2\x14.cubelet.types.ImageR\x06images\"\xa0\x01\n" +
	"\x11ImageVolumeSource\x12C\n" +
	"\treference\x18\x01 \x01(\v2%.cubelet.services.images.v1.ImageSpecR\treference\x12F\n" +
	"\n" +
	"pullPolicy\x18\x02 \x01(\x0e2&.cubelet.services.images.v1.PullPolicyR\n" +
	"pullPolicy*-\n" +
	"\x15ImageStorageMediaType\x12\n" +
	"\n" +
	"\x06docker\x10\x00\x12\b\n" +
	"\x04ext4\x10\x01*5\n" +
	"\n" +
	"PullPolicy\x12\n" +
	"\n" +
	"\x06Always\x10\x00\x12\t\n" +
	"\x05Never\x10\x01\x12\x10\n" +
	"\fIfNotPresent\x10\x022\xd3\x03\n" +
	"\x06Images\x12u\n" +
	"\vCreateImage\x12..cubelet.services.images.v1.CreateImageRequest\x1a6.cubelet.services.images.v1.CreateImageRequestResponse\x12q\n" +
	"\n" +
	"ListImages\x120.cubelet.services.images.v1.CubeListImageRequest\x1a1.cubelet.services.images.v1.CubeListImageResponse\x12q\n" +
	"\fDestroyImage\x12/.cubelet.services.images.v1.DestroyImageRequest\x1a0.cubelet.services.images.v1.DestroyImageResponse\x12l\n" +
	"\vVolumeUtils\x12-.cubelet.services.images.v1.VolumUtilsRequest\x1a..cubelet.services.images.v1.VolumUtilsResponseBNZLgithub.com/tencentcloud/CubeSandbox/CubeMaster/api/services/images/v1;imagesb\x06proto3"

var (
	file_api_services_images_v1_images_proto_rawDescOnce sync.Once
	file_api_services_images_v1_images_proto_rawDescData []byte
)

func file_api_services_images_v1_images_proto_rawDescGZIP() []byte {
	file_api_services_images_v1_images_proto_rawDescOnce.Do(func() {
		file_api_services_images_v1_images_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_images_v1_images_proto_rawDesc), len(file_api_services_images_v1_images_proto_rawDesc)))
	})
	return file_api_services_images_v1_images_proto_rawDescData
}

var file_api_services_images_v1_images_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_services_images_v1_images_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_services_images_v1_images_proto_goTypes = []any{
	(ImageStorageMediaType)(0),         // 0: cubelet.services.images.v1.ImageStorageMediaType
	(PullPolicy)(0),                    // 1: cubelet.services.images.v1.PullPolicy
	(*CreateImageRequest)(nil),         // 2: cubelet.services.images.v1.CreateImageRequest
	(*ImageSpec)(nil),                  // 3: cubelet.services.images.v1.ImageSpec
	(*CreateImageRequestResponse)(nil), // 4: cubelet.services.images.v1.CreateImageRequestResponse
	(*DestroyImageRequest)(nil),        // 5: cubelet.services.images.v1.DestroyImageRequest
	(*DestroyImageResponse)(nil),       // 6: cubelet.services.images.v1.DestroyImageResponse
	(*VolumUtilsRequest)(nil),          // 7: cubelet.services.images.v1.VolumUtilsRequest
	(*VolumUtilsResponse)(nil),         // 8: cubelet.services.images.v1.VolumUtilsResponse
	(*CubeListImageRequest)(nil),       // 9: cubelet.services.images.v1.CubeListImageRequest
	(*CubeListImageResponse)(nil),      // 10: cubelet.services.images.v1.CubeListImageResponse
	(*ImageVolumeSource)(nil),          // 11: cubelet.services.images.v1.ImageVolumeSource
	nil,                                // 12: cubelet.services.images.v1.ImageSpec.AnnotationsEntry
	(*v1.Ret)(nil),                     // 13: cubelet.services.errorcode.v1.Ret
	(*v11.ImageFilter)(nil),            // 14: cubelet.types.ImageFilter
	(*v11.Image)(nil),                  // 15: cubelet.types.Image
}
var file_api_services_images_v1_images_proto_depIdxs = []int32{
	3,  // 0: cubelet.services.images.v1.CreateImageRequest.spec:type_name -> cubelet.services.images.v1.ImageSpec
	12, // 1: cubelet.services.images.v1.ImageSpec.annotations:type_name -> cubelet.services.images.v1.ImageSpec.AnnotationsEntry
	13, // 2: cubelet.services.images.v1.CreateImageRequestResponse.ret:type_name -> cubelet.services.errorcode.v1.Ret
	3,  // 3: cubelet.services.images.v1.DestroyImageRequest.spec:type_name -> cubelet.services.images.v1.ImageSpec
	13, // 4: cubelet.services.images.v1.DestroyImageResponse.ret:type_name -> cubelet.services.errorcode.v1.Ret
	13, // 5: cubelet.services.images.v1.VolumUtilsResponse.ret:type_name -> cubelet.services.errorcode.v1.Ret
	14, // 6: cubelet.services.images.v1.CubeListImageRequest.filter:type_name -> cubelet.types.ImageFilter
	13, // 7: cubelet.services.images.v1.CubeListImageResponse.ret:type_name -> cubelet.services.errorcode.v1.Ret
	15, // 8: cubelet.services.images.v1.CubeListImageResponse.images:type_name -> cubelet.types.Image
	3,  // 9: cubelet.services.images.v1.ImageVolumeSource.reference:type_name -> cubelet.services.images.v1.ImageSpec
	1,  // 10: cubelet.services.images.v1.ImageVolumeSource.pullPolicy:type_name -> cubelet.services.images.v1.PullPolicy
	2,  // 11: cubelet.services.images.v1.Images.CreateImage:input_type -> cubelet.services.images.v1.CreateImageRequest
	9,  // 12: cubelet.services.images.v1.Images.ListImages:input_type -> cubelet.services.images.v1.CubeListImageRequest
	5,  // 13: cubelet.services.images.v1.Images.DestroyImage:input_type -> cubelet.services.images.v1.DestroyImageRequest
	7,  // 14: cubelet.services.images.v1.Images.VolumeUtils:input_type -> cubelet.services.images.v1.VolumUtilsRequest
	4,  // 15: cubelet.services.images.v1.Images.CreateImage:output_type -> cubelet.services.images.v1.CreateImageRequestResponse
	10, // 16: cubelet.services.images.v1.Images.ListImages:output_type -> cubelet.services.images.v1.CubeListImageResponse
	6,  // 17: cubelet.services.images.v1.Images.DestroyImage:output_type -> cubelet.services.images.v1.DestroyImageResponse
	8,  // 18: cubelet.services.images.v1.Images.VolumeUtils:output_type -> cubelet.services.images.v1.VolumUtilsResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_services_images_v1_images_proto_init() }
func file_api_services_images_v1_images_proto_init() {
	if File_api_services_images_v1_images_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_images_v1_images_proto_rawDesc), len(file_api_services_images_v1_images_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_images_v1_images_proto_goTypes,
		DependencyIndexes: file_api_services_images_v1_images_proto_depIdxs,
		EnumInfos:         file_api_services_images_v1_images_proto_enumTypes,
		MessageInfos:      file_api_services_images_v1_images_proto_msgTypes,
	}.Build()
	File_api_services_images_v1_images_proto = out.File
	file_api_services_images_v1_images_proto_goTypes = nil
	file_api_services_images_v1_images_proto_depIdxs = nil
}
