FROM cube-sandbox-int.tencentcloudcr.com/cube-sandbox/sandbox-code:latest

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest yarn pnpm
