// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/errorcode/v1/errorcode.proto

package errorcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                                ErrorCode = 0
	ErrorCode_Unknown                           ErrorCode = -1
	ErrorCode_Success                           ErrorCode = 200
	ErrorCode_Conflict                          ErrorCode = 130409
	ErrorCode_GrpcError                         ErrorCode = 130500
	ErrorCode_ListContainerFailed               ErrorCode = 130504
	ErrorCode_ContainerNotFound                 ErrorCode = 130505
	ErrorCode_RemoveContainerFailed             ErrorCode = 130506
	ErrorCode_CreateContainerFailed             ErrorCode = 130507
	ErrorCode_StartContainerFailed              ErrorCode = 130508
	ErrorCode_BindContainerFailed               ErrorCode = 130511
	ErrorCode_ConcurrentFailed                  ErrorCode = 130513
	ErrorCode_DownloadCodeFailed                ErrorCode = 130514
	ErrorCode_DownloadLayerFailed               ErrorCode = 130516
	ErrorCode_DiskNotEnough                     ErrorCode = 130519
	ErrorCode_DeployCodeTimeout                 ErrorCode = 130524
	ErrorCode_DeployLayerTimeout                ErrorCode = 130525
	ErrorCode_DeployCodeLayerTimeout            ErrorCode = 130526
	ErrorCode_NoSpaceLeftOnDevice               ErrorCode = 130527
	ErrorCode_RunContainerTimeout               ErrorCode = 130539
	ErrorCode_CreateStorageFailed               ErrorCode = 130545
	ErrorCode_CreateImageFailed                 ErrorCode = 130546
	ErrorCode_CreateNetworkFailed               ErrorCode = 130547
	ErrorCode_InitHostFailed                    ErrorCode = 130548
	ErrorCode_SetCubeboxCgroupLimitFailed       ErrorCode = 130549
	ErrorCode_LoadContainerFromMetaDataFailed   ErrorCode = 130550
	ErrorCode_DeleteTaskFailed                  ErrorCode = 130551
	ErrorCode_DeleteContainerFromMetaDataFailed ErrorCode = 130552
	ErrorCode_UpdateLocalMetaDataFailed         ErrorCode = 130553
	ErrorCode_ResolveLocalSpecFailed            ErrorCode = 130554
	ErrorCode_NewContainerMetaDataFailed        ErrorCode = 130555
	ErrorCode_NewTaskFailed                     ErrorCode = 130556
	ErrorCode_WaitTaskFailed                    ErrorCode = 130557
	ErrorCode_StartTaskFailed                   ErrorCode = 130558
	ErrorCode_DestroyStorageFailed              ErrorCode = 130559
	ErrorCode_CreateShimlogFailed               ErrorCode = 130560
	ErrorCode_DestroyShimlogFailed              ErrorCode = 130561
	ErrorCode_CreateCgroupFailed                ErrorCode = 130562
	ErrorCode_DestroyCgroupFailed               ErrorCode = 130563
	ErrorCode_DestroyNetworkFailed              ErrorCode = 130564
	ErrorCode_UpdateLocalImageSpecFailed        ErrorCode = 130565
	ErrorCode_CreateVolumeFailed                ErrorCode = 130566
	ErrorCode_HostDiskNotEnough                 ErrorCode = 130567
	ErrorCode_PreConditionFailed                ErrorCode = 130568
	ErrorCode_DestroyImageFailed                ErrorCode = 130569
	ErrorCode_TaskPauseFailed                   ErrorCode = 130588
	ErrorCode_TaskResumeFailed                  ErrorCode = 130589
	ErrorCode_InitCommandPathError              ErrorCode = 130445
	ErrorCode_ContainerStateExitedByUser        ErrorCode = 130451
	ErrorCode_PullImageFailed                   ErrorCode = 130456
	ErrorCode_PullImageTimeOut                  ErrorCode = 130457
	ErrorCode_PortBindingFailed                 ErrorCode = 130459
	ErrorCode_PullImageTokenAuthFailed          ErrorCode = 130460
	ErrorCode_SquashfsMountFailed               ErrorCode = 130461
	ErrorCode_LoadUserProcTimeout               ErrorCode = 130462
	ErrorCode_ConcurrentLimited                 ErrorCode = 130480
	ErrorCode_PreStopTimeOut                    ErrorCode = 130481
	ErrorCode_PreStopFailed                     ErrorCode = 130482
	ErrorCode_InvalidParamFormat                ErrorCode = 130483
	ErrorCode_TaskStateInvalid                  ErrorCode = 130490
	// 尝试在沙箱中执行命令失败
	ErrorCode_ExecCommandInSandboxFailed ErrorCode = 130497
	// 应用快照不存在
	ErrorCode_AppSnapshotNotExist ErrorCode = 130498
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:      "OK",
		-1:     "Unknown",
		200:    "Success",
		130409: "Conflict",
		130500: "GrpcError",
		130504: "ListContainerFailed",
		130505: "ContainerNotFound",
		130506: "RemoveContainerFailed",
		130507: "CreateContainerFailed",
		130508: "StartContainerFailed",
		130511: "BindContainerFailed",
		130513: "ConcurrentFailed",
		130514: "DownloadCodeFailed",
		130516: "DownloadLayerFailed",
		130519: "DiskNotEnough",
		130524: "DeployCodeTimeout",
		130525: "DeployLayerTimeout",
		130526: "DeployCodeLayerTimeout",
		130527: "NoSpaceLeftOnDevice",
		130539: "RunContainerTimeout",
		130545: "CreateStorageFailed",
		130546: "CreateImageFailed",
		130547: "CreateNetworkFailed",
		130548: "InitHostFailed",
		130549: "SetCubeboxCgroupLimitFailed",
		130550: "LoadContainerFromMetaDataFailed",
		130551: "DeleteTaskFailed",
		130552: "DeleteContainerFromMetaDataFailed",
		130553: "UpdateLocalMetaDataFailed",
		130554: "ResolveLocalSpecFailed",
		130555: "NewContainerMetaDataFailed",
		130556: "NewTaskFailed",
		130557: "WaitTaskFailed",
		130558: "StartTaskFailed",
		130559: "DestroyStorageFailed",
		130560: "CreateShimlogFailed",
		130561: "DestroyShimlogFailed",
		130562: "CreateCgroupFailed",
		130563: "DestroyCgroupFailed",
		130564: "DestroyNetworkFailed",
		130565: "UpdateLocalImageSpecFailed",
		130566: "CreateVolumeFailed",
		130567: "HostDiskNotEnough",
		130568: "PreConditionFailed",
		130569: "DestroyImageFailed",
		130588: "TaskPauseFailed",
		130589: "TaskResumeFailed",
		130445: "InitCommandPathError",
		130451: "ContainerStateExitedByUser",
		130456: "PullImageFailed",
		130457: "PullImageTimeOut",
		130459: "PortBindingFailed",
		130460: "PullImageTokenAuthFailed",
		130461: "SquashfsMountFailed",
		130462: "LoadUserProcTimeout",
		130480: "ConcurrentLimited",
		130481: "PreStopTimeOut",
		130482: "PreStopFailed",
		130483: "InvalidParamFormat",
		130490: "TaskStateInvalid",
		130497: "ExecCommandInSandboxFailed",
		130498: "AppSnapshotNotExist",
	}
	ErrorCode_value = map[string]int32{
		"OK":                                0,
		"Unknown":                           -1,
		"Success":                           200,
		"Conflict":                          130409,
		"GrpcError":                         130500,
		"ListContainerFailed":               130504,
		"ContainerNotFound":                 130505,
		"RemoveContainerFailed":             130506,
		"CreateContainerFailed":             130507,
		"StartContainerFailed":              130508,
		"BindContainerFailed":               130511,
		"ConcurrentFailed":                  130513,
		"DownloadCodeFailed":                130514,
		"DownloadLayerFailed":               130516,
		"DiskNotEnough":                     130519,
		"DeployCodeTimeout":                 130524,
		"DeployLayerTimeout":                130525,
		"DeployCodeLayerTimeout":            130526,
		"NoSpaceLeftOnDevice":               130527,
		"RunContainerTimeout":               130539,
		"CreateStorageFailed":               130545,
		"CreateImageFailed":                 130546,
		"CreateNetworkFailed":               130547,
		"InitHostFailed":                    130548,
		"SetCubeboxCgroupLimitFailed":       130549,
		"LoadContainerFromMetaDataFailed":   130550,
		"DeleteTaskFailed":                  130551,
		"DeleteContainerFromMetaDataFailed": 130552,
		"UpdateLocalMetaDataFailed":         130553,
		"ResolveLocalSpecFailed":            130554,
		"NewContainerMetaDataFailed":        130555,
		"NewTaskFailed":                     130556,
		"WaitTaskFailed":                    130557,
		"StartTaskFailed":                   130558,
		"DestroyStorageFailed":              130559,
		"CreateShimlogFailed":               130560,
		"DestroyShimlogFailed":              130561,
		"CreateCgroupFailed":                130562,
		"DestroyCgroupFailed":               130563,
		"DestroyNetworkFailed":              130564,
		"UpdateLocalImageSpecFailed":        130565,
		"CreateVolumeFailed":                130566,
		"HostDiskNotEnough":                 130567,
		"PreConditionFailed":                130568,
		"DestroyImageFailed":                130569,
		"TaskPauseFailed":                   130588,
		"TaskResumeFailed":                  130589,
		"InitCommandPathError":              130445,
		"ContainerStateExitedByUser":        130451,
		"PullImageFailed":                   130456,
		"PullImageTimeOut":                  130457,
		"PortBindingFailed":                 130459,
		"PullImageTokenAuthFailed":          130460,
		"SquashfsMountFailed":               130461,
		"LoadUserProcTimeout":               130462,
		"ConcurrentLimited":                 130480,
		"PreStopTimeOut":                    130481,
		"PreStopFailed":                     130482,
		"InvalidParamFormat":                130483,
		"TaskStateInvalid":                  130490,
		"ExecCommandInSandboxFailed":        130497,
		"AppSnapshotNotExist":               130498,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_services_errorcode_v1_errorcode_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_services_errorcode_v1_errorcode_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_services_errorcode_v1_errorcode_proto_rawDescGZIP(), []int{0}
}

type Ret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       ErrorCode              `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3,enum=cubelet.services.errorcode.v1.ErrorCode" json:"ret_code,omitempty"`
	RetMsg        string                 `protobuf:"bytes,2,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ret) Reset() {
	*x = Ret{}
	mi := &file_api_services_errorcode_v1_errorcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ret) ProtoMessage() {}

func (x *Ret) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_errorcode_v1_errorcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ret.ProtoReflect.Descriptor instead.
func (*Ret) Descriptor() ([]byte, []int) {
	return file_api_services_errorcode_v1_errorcode_proto_rawDescGZIP(), []int{0}
}

func (x *Ret) GetRetCode() ErrorCode {
	if x != nil {
		return x.RetCode
	}
	return ErrorCode_OK
}

func (x *Ret) GetRetMsg() string {
	if x != nil {
		return x.RetMsg
	}
	return ""
}

var File_api_services_errorcode_v1_errorcode_proto protoreflect.FileDescriptor

const file_api_services_errorcode_v1_errorcode_proto_rawDesc = "" +
	"\n" +
	")api/services/errorcode/v1/errorcode.proto\x12\x1dcubelet.services.errorcode.v1\"c\n" +
	"\x03Ret\x12C\n" +
	"\bret_code\x18\x01 \x01(\x0e2(.cubelet.services.errorcode.v1.ErrorCodeR\aretCode\x12\x17\n" +
	"\aret_msg\x18\x02 \x01(\tR\x06retMsg*\xe4\f\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x14\n" +
	"\aUnknown\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\f\n" +
	"\aSuccess\x10\xc8\x01\x12\x0e\n" +
	"\bConflict\x10\xe9\xfa\a\x12\x0f\n" +
	"\tGrpcError\x10\xc4\xfb\a\x12\x19\n" +
	"\x13ListContainerFailed\x10\xc8\xfb\a\x12\x17\n" +
	"\x11ContainerNotFound\x10\xc9\xfb\a\x12\x1b\n" +
	"\x15RemoveContainerFailed\x10\xca\xfb\a\x12\x1b\n" +
	"\x15CreateContainerFailed\x10\xcb\xfb\a\x12\x1a\n" +
	"\x14StartContainerFailed\x10\xcc\xfb\a\x12\x19\n" +
	"\x13BindContainerFailed\x10\xcf\xfb\a\x12\x16\n" +
	"\x10ConcurrentFailed\x10\xd1\xfb\a\x12\x18\n" +
	"\x12DownloadCodeFailed\x10\xd2\xfb\a\x12\x19\n" +
	"\x13DownloadLayerFailed\x10\xd4\xfb\a\x12\x13\n" +
	"\rDiskNotEnough\x10\xd7\xfb\a\x12\x17\n" +
	"\x11DeployCodeTimeout\x10\xdc\xfb\a\x12\x18\n" +
	"\x12DeployLayerTimeout\x10\xdd\xfb\a\x12\x1c\n" +
	"\x16DeployCodeLayerTimeout\x10\xde\xfb\a\x12\x19\n" +
	"\x13NoSpaceLeftOnDevice\x10\xdf\xfb\a\x12\x19\n" +
	"\x13RunContainerTimeout\x10\xeb\xfb\a\x12\x19\n" +
	"\x13CreateStorageFailed\x10\xf1\xfb\a\x12\x17\n" +
	"\x11CreateImageFailed\x10\xf2\xfb\a\x12\x19\n" +
	"\x13CreateNetworkFailed\x10\xf3\xfb\a\x12\x14\n" +
	"\x0eInitHostFailed\x10\xf4\xfb\a\x12!\n" +
	"\x1bSetCubeboxCgroupLimitFailed\x10\xf5\xfb\a\x12%\n" +
	"\x1fLoadContainerFromMetaDataFailed\x10\xf6\xfb\a\x12\x16\n" +
	"\x10DeleteTaskFailed\x10\xf7\xfb\a\x12'\n" +
	"!DeleteContainerFromMetaDataFailed\x10\xf8\xfb\a\x12\x1f\n" +
	"\x19UpdateLocalMetaDataFailed\x10\xf9\xfb\a\x12\x1c\n" +
	"\x16ResolveLocalSpecFailed\x10\xfa\xfb\a\x12 \n" +
	"\x1aNewContainerMetaDataFailed\x10\xfb\xfb\a\x12\x13\n" +
	"\rNewTaskFailed\x10\xfc\xfb\a\x12\x14\n" +
	"\x0eWaitTaskFailed\x10\xfd\xfb\a\x12\x15\n" +
	"\x0fStartTaskFailed\x10\xfe\xfb\a\x12\x1a\n" +
	"\x14DestroyStorageFailed\x10\xff\xfb\a\x12\x19\n" +
	"\x13CreateShimlogFailed\x10\x80\xfc\a\x12\x1a\n" +
	"\x14DestroyShimlogFailed\x10\x81\xfc\a\x12\x18\n" +
	"\x12CreateCgroupFailed\x10\x82\xfc\a\x12\x19\n" +
	"\x13DestroyCgroupFailed\x10\x83\xfc\a\x12\x1a\n" +
	"\x14DestroyNetworkFailed\x10\x84\xfc\a\x12 \n" +
	"\x1aUpdateLocalImageSpecFailed\x10\x85\xfc\a\x12\x18\n" +
	"\x12CreateVolumeFailed\x10\x86\xfc\a\x12\x17\n" +
	"\x11HostDiskNotEnough\x10\x87\xfc\a\x12\x18\n" +
	"\x12PreConditionFailed\x10\x88\xfc\a\x12\x18\n" +
	"\x12DestroyImageFailed\x10\x89\xfc\a\x12\x15\n" +
	"\x0fTaskPauseFailed\x10\x9c\xfc\a\x12\x16\n" +
	"\x10TaskResumeFailed\x10\x9d\xfc\a\x12\x1a\n" +
	"\x14InitCommandPathError\x10\x8d\xfb\a\x12 \n" +
	"\x1aContainerStateExitedByUser\x10\x93\xfb\a\x12\x15\n" +
	"\x0fPullImageFailed\x10\x98\xfb\a\x12\x16\n" +
	"\x10PullImageTimeOut\x10\x99\xfb\a\x12\x17\n" +
	"\x11PortBindingFailed\x10\x9b\xfb\a\x12\x1e\n" +
	"\x18PullImageTokenAuthFailed\x10\x9c\xfb\a\x12\x19\n" +
	"\x13SquashfsMountFailed\x10\x9d\xfb\a\x12\x19\n" +
	"\x13LoadUserProcTimeout\x10\x9e\xfb\a\x12\x17\n" +
	"\x11ConcurrentLimited\x10\xb0\xfb\a\x12\x14\n" +
	"\x0ePreStopTimeOut\x10\xb1\xfb\a\x12\x13\n" +
	"\rPreStopFailed\x10\xb2\xfb\a\x12\x18\n" +
	"\x12InvalidParamFormat\x10\xb3\xfb\a\x12\x16\n" +
	"\x10TaskStateInvalid\x10\xba\xfb\a\x12 \n" +
	"\x1aExecCommandInSandboxFailed\x10\xc1\xfb\a\x12\x19\n" +
	"\x13AppSnapshotNotExist\x10\xc2\xfb\aBTZRgithub.com/tencentcloud/CubeSandbox/CubeMaster/api/services/errorcode/v1;errorcodeb\x06proto3"

var (
	file_api_services_errorcode_v1_errorcode_proto_rawDescOnce sync.Once
	file_api_services_errorcode_v1_errorcode_proto_rawDescData []byte
)

func file_api_services_errorcode_v1_errorcode_proto_rawDescGZIP() []byte {
	file_api_services_errorcode_v1_errorcode_proto_rawDescOnce.Do(func() {
		file_api_services_errorcode_v1_errorcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_errorcode_v1_errorcode_proto_rawDesc), len(file_api_services_errorcode_v1_errorcode_proto_rawDesc)))
	})
	return file_api_services_errorcode_v1_errorcode_proto_rawDescData
}

var file_api_services_errorcode_v1_errorcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_services_errorcode_v1_errorcode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_services_errorcode_v1_errorcode_proto_goTypes = []any{
	(ErrorCode)(0), // 0: cubelet.services.errorcode.v1.ErrorCode
	(*Ret)(nil),    // 1: cubelet.services.errorcode.v1.Ret
}
var file_api_services_errorcode_v1_errorcode_proto_depIdxs = []int32{
	0, // 0: cubelet.services.errorcode.v1.Ret.ret_code:type_name -> cubelet.services.errorcode.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_services_errorcode_v1_errorcode_proto_init() }
func file_api_services_errorcode_v1_errorcode_proto_init() {
	if File_api_services_errorcode_v1_errorcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_errorcode_v1_errorcode_proto_rawDesc), len(file_api_services_errorcode_v1_errorcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_services_errorcode_v1_errorcode_proto_goTypes,
		DependencyIndexes: file_api_services_errorcode_v1_errorcode_proto_depIdxs,
		EnumInfos:         file_api_services_errorcode_v1_errorcode_proto_enumTypes,
		MessageInfos:      file_api_services_errorcode_v1_errorcode_proto_msgTypes,
	}.Build()
	File_api_services_errorcode_v1_errorcode_proto = out.File
	file_api_services_errorcode_v1_errorcode_proto_goTypes = nil
	file_api_services_errorcode_v1_errorcode_proto_depIdxs = nil
}
